name: custom-levels
version: 0.98
description:
author: chaoscrasher & junkdudehd
main: com.jb1services.mc.junkdudehd.customlevels.main.CustomLevelsPlugin

commands:
  clevel:
    description: Shows your custom level!
    usage: use /clevel