name: simpleloans
version: 0.96
description:
author: chaoscrasher & muttley
main: com.jb1services.mc.muttley.simpleloans.main.SimpleLoansPlugin

commands:
  loan:
    description: Allows you to loan to other people!
    usage: use /loan offer <loanee> <amount> <days> <interest>, /loan accept <loanShark>, loan deny <loanShsrk>, loan list live|hosted|offered|offeredTo 